
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew awscli
brew bdw-gc
brew carthage
brew cmake
brew coreutils
brew cowsay
brew ctags
brew direnv
brew freetype
brew gdbm
brew gettext
brew ghq
brew git
brew git-now
brew glide
brew gmp
brew gnu-getopt
brew gnu-typist
brew go
brew heroku
brew hub
brew icu4c
brew imagemagick
brew jemalloc
brew jpeg
brew jq
brew libevent
brew libpng
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvterm
brew libyaml
brew lua
brew luajit
brew mas
brew maven
brew msgpack
brew neovim
brew nettle
brew nkf
brew nmap
brew node
brew nspr
brew oniguruma
brew openssl
brew openssl@1.1
brew pcre
brew peco
brew pkg-config
brew pwgen
brew python3
brew rbenv
brew readline
brew reattach-to-user-namespace
brew ruby-build
brew sl
brew spidermonkey
brew sqlite
brew stoken
brew tcpflow
brew terraform
brew the_silver_searcher
brew tig
brew tmux
brew tomcat
brew tree
brew unibilium
brew vim --with-lua
brew w3m
brew watch
brew xz
brew yajl
brew zsh

tap caskroom/cask
cask slack
cask atom
cask toggl
cask ganttproject
cask flux
cask amazon-music
cask appcleaner
cask yummy-ftp
cask macdown
cask evernote
cask iterm2
cask dropbox
cask docker
cask dash
cask clipy
cask caffeine
cask 4k-youtube-to-mp3
cask sequel-pro
cask google-chrome
cask java
cask alfred
cask mysqlworkbench

tap neovim/neovim

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 973134470 Be Focused (1.6.2)
appstore 1055511498 Day One (2.5.4)
appstore 1180531112 DeskApp for YouTube (1.1.1)
appstore 441258766 Magnet (2.1.0)
appstore 748212890 Memory Cleaner (2.4.4)
appstore 929507092 PhotoScapeX (2.6.3)
appstore 880001334 Reeder (3.1.2)
