
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew awscli
brew bdw-gc
brew carthage
brew cmake
brew coreutils
brew cowsay
brew ctags
brew direnv
brew freetype
brew gdbm
brew gettext
brew ghq
brew git
brew git-now
brew glide
brew gmp
brew gnu-getopt
brew gnu-typist
brew go
brew heroku
brew hub
brew icu4c
brew imagemagick
brew jemalloc
brew jpeg
brew jq
brew libevent
brew libpng
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvterm
brew libyaml
brew lua
brew luajit
brew mas
brew maven
brew msgpack
brew neovim
brew nettle
brew nkf
brew nmap
brew node
brew nspr
brew oniguruma
brew openssl
brew openssl@1.1
brew pcre
brew peco
brew pkg-config
brew pwgen
brew rbenv
brew readline
brew reattach-to-user-namespace
brew ruby-build
brew sl
brew spidermonkey
brew sqlite
brew stoken
brew tcpflow
brew terraform
brew the_silver_searcher
brew tig
brew tmux
brew tomcat
brew tree
brew unibilium
brew vim --with-lua
brew w3m
brew watch
brew xz
brew yajl
brew zsh

tap caskroom/cask

tap neovim/neovim

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew awsebcli
brew golang
brew python3

# Other Cask applications
cask alfred
cask appcleaner
cask atom
cask caffeine
cask clipy
cask dash
cask docker
cask dropbox
cask evernote
cask flux
cask google-chrome
cask iterm2
cask java
cask mysqlworkbench
cask rescuetime
cask sequel-pro
cask slack
