
# tap repositories and their packages

tap caskroom/cask
cask atom
cask ganttproject
cask flux
cask appcleaner
cask macdown
cask evernote
cask iterm2
cask dropbox
cask docker
cask clipy
cask caffeine
cask sequel-pro
cask google-chrome
cask alfred
cask mysqlworkbench

tap homebrew/core
brew autoconf
brew automake
brew awscli
brew bdw-gc
brew carthage
brew cmake
brew coreutils
brew cowsay
brew ctags
brew direnv
brew freetype
brew gdbm
brew gettext
brew ghq
brew git
brew git-now
brew glide
brew gmp
brew gnu-getopt
brew gnu-typist
brew go
brew heroku
brew hub
brew imagemagick
brew jemalloc
brew jpeg
brew jq
brew libevent
brew libpng
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvterm
brew libyaml
brew lua
brew mas
brew maven
brew msgpack
brew neovim
brew nettle
brew nkf
brew nmap
brew nspr
brew oniguruma
brew openssl
brew pcre
brew peco
brew pkg-config
brew pwgen
brew python3
brew rbenv
brew readline
brew reattach-to-user-namespace
brew ruby-build
brew sl
brew spidermonkey
brew sqlite
brew stoken
brew tcpflow
brew terraform
brew the_silver_searcher
brew tig
brew tmux
brew tomcat
brew tree
brew unibilium
brew vim --with-lua
brew w3m
brew watch
brew xz
brew yajl
brew zsh

tap neovim/neovim

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew drafter --HEAD

# Cask applications
cask clipmenu

# App Store applications
appstore 748212890 Cleaner for Memory (2.4.2)
appstore 449589707 Dash (3.2.3)
appstore 441258766 Magnet (2.1.0)
appstore 880001334 Reeder (3.0.5)
appstore 425955336 Skitch (2.8)
